### ISSUE TITLE
A couple of questions.

### ISSUE THREAD

**Issue by EasternSun300** [ChazDazzle/fpdb-chaz#27]
Hello is the all in graph ported to qt5? it used to work before but now using your repo it is identical to the winnings graph. opened the database and values are the same for the allinev and winnings collumns. could you try to fix this? even with installed pypoker-eval graphs are the same. @ChazDazzle 

EDIT - Fixed the all in ev graph being the same as the greenline

**Comment by EasternSun300** [comment]
Also is there an easy way of disabling play money hands for graphs and positional stats and tourney stats? delete playmoney part from filters.py?
edit add playmoney in import filters?

**Comment by EasternSun300** [comment]
Also Guireplayer looks ported to qt5. i cant seem to find in which commit - import GuiReplayer was removed so i can reenable it.

so far i added

def tab_replayer(self,widget, data=None):
	new_re_thread = GuiReplayer.GuiReplayer(self.config, self.sql, self.window, self)
	self.threads.append(new_re_thread)
	self.add_and_display_tab(new_re_thread, _("Replayer"))
it adds a tab and when clicked it shows the old replayer but without buttons or anything

https://imgur.com/a/7LAwodL

am i doing something wrong?

**Comment by EasternSun300** [comment]
Also im trying to change the default tab from help to auto import tab.
in fpdb.pyw i changed this code - line 1160 -
        # create the first tab
        self.tab_main_help(None, None)
to
        # create the first tab
        self.tab_auto_import(None, None)
console gives me this when i launch fpdb.pyw
Traceback (most recent call last):
  File "fpdb.pyw", line 1321, in <module>
    me = fpdb()
  File "fpdb.pyw", line 1163, in __init__
    self.tab_auto_import(None, None)
  File "fpdb.pyw", line 1010, in tab_auto_import
    new_aimp_thread = GuiAutoImport.GuiAutoImport(self.settings, self.config, self.sql, self)
AttributeError: 'fpdb' object has no attribute 'settings'

Can you help me out?

**Comment by EasternSun300** [comment]
Also is there a way to start hud_main with --minimized?
changes in GuiAutoImport.py line 212 -
command = 'python "'+path+'\\HUD_main.pyw" ' + self.settings['cl_options']
to
command = 'python "'+path+'\\HUD_main.pyw --minimized" ' + self.settings['cl_options']
or
command = 'python "'+path+'\\HUD_main.pyw" --minimized ' + self.settings['cl_options']
doesnt do what i want
Edit - starting fpdb.pyw with --minimized minimizes only the main window HUD_main is still maximized


EDIT - Fixed
